name: "Unit test"

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use oxr463/setup-leiningen
        uses: ./
        with:
          exec: |
            lein test